apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kuma.io/sidecar-injection: enabled
    traffic.kuma.io/exclude-inbound-ports: "53"
    traffic.kuma.io/exclude-outbound-ports: "53"
  name: pihole
---
apiVersion: v1
data:
  adlists.list: |
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/porn.txt
kind: ConfigMap
metadata:
  labels:
    app: pihole
    chart: pihole-2.4.2
    heritage: Helm
    release: pihole
  name: pihole-adlists
---
apiVersion: v1
data:
  02-custom.conf: |
    addn-hosts=/etc/addn-hosts
  05-pihole-custom-cname.conf: ""
  addn-hosts: ""
kind: ConfigMap
metadata:
  labels:
    app: pihole
    chart: pihole-2.4.2
    heritage: Helm
    release: pihole
  name: pihole-custom-dnsmasq
---
apiVersion: v1
data:
  password: YWRtaW4=
kind: Secret
metadata:
  labels:
    app: pihole
    chart: pihole-2.4.2
    heritage: Helm
    release: pihole
  name: pihole-password
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
    chart: pihole-2.4.2
    heritage: Helm
    release: pihole
  name: pihole-dns-tcp
spec:
  externalTrafficPolicy: Local
  ports:
  - name: dns
    port: 53
    protocol: TCP
    targetPort: dns
  selector:
    app: pihole
    release: pihole
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
    chart: pihole-2.4.2
    heritage: Helm
    release: pihole
  name: pihole-dns-udp
spec:
  externalTrafficPolicy: Local
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  selector:
    app: pihole
    release: pihole
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
    chart: pihole-2.4.2
    heritage: Helm
    release: pihole
  name: pihole-web
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: pihole
    release: pihole
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
    chart: pihole-2.4.2
    heritage: Helm
    release: pihole
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
      release: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum.config.adlists: b582356f8873a7872e9907fa0d786ca31160014208ea178955a4e6b671412b9
        checksum.config.blacklist: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546
        checksum.config.dnsmasqConfig: 3c2ec553e09f3e7915c0bcaf0661ffd6881695bae9e5716a371b4567d0fe850
        checksum.config.ftl: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546
        checksum.config.regex: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546
        checksum.config.staticDhcpConfig: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546
        checksum.config.whitelist: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546
      labels:
        app: pihole
        release: pihole
    spec:
      containers:
      - env:
        - name: WEB_PORT
          value: "80"
        - name: VIRTUAL_HOST
          value: pi.hole
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-password
        - name: PIHOLE_DNS_
          value: 127.0.0.1#5353;127.0.0.1#5353
        image: pihole/pihole:2021.10
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /admin.index.php
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 5
        name: pihole
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 53
          name: dns
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 67
          name: client-udp
          protocol: UDP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin.index.php
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 5
        resources: {}
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /etc/pihole
          name: config
        - mountPath: /etc/dnsmasq.d/02-custom.conf
          name: custom-dnsmasq
          subPath: 02-custom.conf
        - mountPath: /etc/addn-hosts
          name: custom-dnsmasq
          subPath: addn-hosts
        - mountPath: /etc/dnsmasq.d/05-pihole-custom-cname.conf
          name: custom-dnsmasq
          subPath: 05-pihole-custom-cname.conf
        - mountPath: /etc/pihole/adlists.list
          name: adlists
          subPath: adlists.list
      - args:
        - --loglevel
        - debug
        - proxy-dns
        - --port
        - "5353"
        - --upstream
        - https://1.1.1.3/dns-query
        - --upstream
        - https://1.0.0.3/dns-query
        image: cloudflare/cloudflared:2021.9.1
        imagePullPolicy: IfNotPresent
        name: cloudflared
        ports:
        - containerPort: 5353
          name: dns
          protocol: TCP
        - containerPort: 5353
          name: dns-udp
          protocol: UDP
      dnsConfig:
        nameservers:
        - 127.0.0.1
        - 8.8.8.8
      dnsPolicy: None
      hostNetwork: false
      hostname: null
      volumes:
      - emptyDir: {}
        name: config
      - configMap:
          defaultMode: 420
          name: pihole-custom-dnsmasq
        name: custom-dnsmasq
      - configMap:
          defaultMode: 420
          name: pihole-adlists
        name: adlists
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  name: pihole-smoke-test
spec:
  containers:
  - command:
    - sh
    - -c
    - curl http://pihole-web:80/
    image: curlimages/curl
    imagePullPolicy: IfNotPresent
    name: hook1-container
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
