apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pihole.yaml

patches:
- path: patch-service-loadbalancer.yaml
  target:
    kind: Service
    name: pihole-dns-tcp
- path: patch-service-loadbalancer.yaml
  target:
    kind: Service
    name: pihole-dns-udp
- path: patch-remove-dhcp.yaml
  target:
    kind: Service
    name: pihole-dns-udp
