- op: add
  path: /spec/template/spec/containers/-
  value:
    image: pihole/pihole:v5.8.1
    imagePullPolicy: IfNotPresent
    args: ["dns-proxy", "-port", "5053", "--upstream", "https://1.1.1.3/dns-query", "--upstream", "https://1.0.0.3/dns-query"]
    name: cloudflared
    ports:
    - containerPort: 5353
      name: dns
      protocol: TCP
    - containerPort: 5353
      name: dns-udp
      protocol: UDP
